[colophon%discrete%notitle%nonfacing,toclevels=0]
= Copyright
:isbn-cor: 978-65-988962-0-1
:isbn-pb: 978-65-988962-1-8

Tradução em português autorizada da obra +
_Fluent Python, 2nd Edition_ ISBN 978-1-492-05635-5
© 2022 Luciano Ramalho. +
Esta tradução é publicada e vendida com a permissão da O'Reilly Media, Inc.,
detentora dos direitos para publicação e venda desta obra.

© 2025 Luciano Ramalho. +
_Python Fluente, 2ª edição_ está publicado sob a licença
_Atribuição-NãoComercial-CompartilhaIgual 4.0 Internacional_ 
«CC BY-NC-SA 4.0» [.small]#&#91;fpy.li/ccby&#93;#. +
O autor mantém uma versão online em https://PythonFluente.com.

Autor: Luciano Ramalho +
Título: Python Fluente, 2ª edição, volume 1: dados e funções +
Primeira edição: 2015 +
Edição atual: setembro/2025 +
{revisao}ª revisão: `pyfl-vol1-rev{revisao}-cor.pdf`

Tradução da 2ª edição: Paulo Candido de Oliveira Filho +
Ilustração de capa: Thiago Castor (xilogravura "Calango") +
Design da capa: Luciano Ramalho, Zander Catta Preta @ Z•Edições +
Design do miolo: Luciano Ramalho, com Asciidoctor +
Ficha catalográfica: Edison Luís dos Santos

Publisher: Heinar Maracy @ Z•Edições

----
R135p   Ramalho, Luciano.

        Python Fluente, 2a edição, volume 1: Dados e funções /
        Luciano Ramalho - São Paulo, SP: Z.Edições, 2025.
        397 p.; il.; cor; 17cm x 24cm

        ISBN: 978-65-988962-0-1 (vol.1, cor)
        1.Informática. 2.Linguagem de Programação. 3.Python.
        4.Metaprogramação.

        I.Título II.Dados e funções III.RAMALHO, Luciano.
            
                                                            CDU: 004.438
                                                            CDD: 005.133
----
