= Python Fluente:  2ª edição, volume 1&#x3a; dados e funções
:doctype: book
:media: prepress
:hide-uri-scheme:
:pdf-page-size: [17cm, 24cm]
:source-highlighter: rouge
:author: Luciano Ramalho
:lang: pt_BR
:language: asciidoctor
:xrefstyle: short
:sectnums:
:sectnumlevels: 4
:sectlinks:
:data-uri:
:toc: macro
:toclevels: 2
:!chapter-signifier:
include::../print/attrib-print-pt-br.adoc[]
include::titulos-vol1.adoc[]

[colophon%notitle%nonfacing]
= Colophon

Python Fluente, 2ª edição, volume 1: dados e funções

(C) 2025 Luciano Ramalho

Tradução autorizada de _Fluent Python Second Edition_ (O'Reilly, 2022)

Tradução: Paulo Candido Oliveira Filho

Revisão: Luciano Ramalho, com colaborações da comunidade Python

Capa: ???

Miolo: feito com Asciidoctor por Luciano Ramalho.

3ª pré-impressão (`pyfl-vol1-pre3.pdf`)

toc::[]

include::Prefacio.adoc[]

[[data_structures_part]]
= Parte I: Estruturas de dados
:sectnums:

include::cap01.adoc[]
include::cap02.adoc[]
include::cap03.adoc[]
include::cap04.adoc[]
include::cap05.adoc[]
include::cap06.adoc[]

[[function_objects_part]]
= Parte II.a: Funções como objetos

[NOTE]
====
Esta edição impressa do _Python Fluente, segunda edição_
foi publicada em três volumes, com oito capítulos por volume.

A Parte II ficou dividida entre os Volumes 1 e 2.

Os capítulos 7 e 8 estão neste Volume 1.

A Parte II.b está no Volume 2, e também na Web:

«Capítulo 9—Decoradores e Clausuras» [.small]#&#91;fpy.li/5c&#93;#

«Capítulo 10—Padrões de projeto com funções» [.small]#&#91;fpy.li/5d&#93;#.
====


include::cap07.adoc[]
include::cap08.adoc[]