# Guia de Estilo
:toc:
:toc-title: Seções
:sectnums:

Padrões gráficos e de linguagem adotados nesta tradução.

## Dicas de formatação

### Uso de maiúsculas em títulos

Somente a primeira letra do título das partes, capítulos e seções deve estar em maiúsculas
(além de nomes próprios ;-).

Padrão: +
*Aventuras aquáticas ao longo do Amazonas*

Fora do padrão: +
*Aventuras Aquáticas ao Longo do Amazonas*

### Código dentro do texto corrido

`Identificadores` de Python devem ser marcados no Asciidoc como `pass:[`monospace`]` (delimitado por crases, `chr(96)`, Unicode GRAVE ACCENT).

Nos identificadores `+__dunder__+`, é preciso colocar um par de `pass:[+]` dentro das crases, assim: `pass:[`+__dunder__+`]`.

Ver https://docs.asciidoctor.org/asciidoc/latest/text/literal-monospace/[literal monospace] na documentação do Asciidoctor.

### Reiniciar numeração de exemplos e figuras por capítulo

Logo abaixo do título do capítulo, zere o atribuitos `:example-number:` e `:figure-number:`.

Exemplo de `cap06.adoc`:

++++
<pre>
[[mutability_and_references]]
== Referências, Mutabilidade, e Memória
:example-number: 0
:figure-number: 0
</pre>
++++
