= Python Fluente, Segunda Edição (2023)
:doctype: book
:author: Luciano Ramalho
:lang: pt_BR
:language: asciidoctor
include::atributos-pt_BR.adoc[]
:xrefstyle: short
:sectnums:
:sectlinks:
:data-uri:
:toc: left
:toclevels: 2
:!chapter-signifier:

[preface]
== Sobre esta tradução

_Python Fluente, Segunda Edição_
é uma tradução direta de _Fluent Python, Second Edition_ (O'Reilly, 2022).
Não é uma obra derivada de _Python Fluente_ (Novatec, 2015).

A presente tradução foi autorizada pela O'Reilly Media para distribuição nos termos da licença
https://creativecommons.org/licenses/by-nc-nd/4.0/deed.pt_BR[CC BY-NC-ND].
Os arquivos-fonte em formato _Asciidoc_ estão no repositório público
https://github.com/pythonfluente/pythonfluente2e.


[NOTE]
====
Esta tradução está em construção.
No sumário, capítulos ainda não traduzidos estão marcados com o símbolo 🚧 (em obras).

Os links com colchetes <<assim>> não funcionam porque são referências cruzadas
para capítulos ainda não publicados.
Eles passarão a funcionar automaticamente quando seus destinos estiverem no ar.

Priorizamos os capítulos 6, 8, 13, 19, 20, e 21. para apoiar o curso _Python Engineer_
a ser lançado pela https://www.linuxtips.io/[LINUXtips] em 2023.
Depois do capítulo 21, os capítulos restantes serão traduzidos em ordem do 1 ao 24.

No momento não precisamos de ajuda para traduzir, mas correções ou
sugestões de melhorias são muito bem vindas!
Para contribuir, veja os
https://github.com/pythonfluente/pythonfluente2e/issues[__issues__]
no repositório https://github.com/pythonfluente/pythonfluente2e.
====

=== Histórico das traduções

Escrevi a primeira e a segunda edições deste livro originalmente em inglês,
para serem mais facilmente distribuídas no mercado internacional.

Cedi os direitos exclusivos para a O'Reilly Media,
nos termos usuais de contratos com editoras famosas:
elas ficam com a maior parte do lucro, o direito de publicar, e
o direito de vender licenças para tradução em outros idiomas.

Até 2022, a primeira edição foi publicada nesses idiomas:

. inglês,
. português brasileiro,
. chinês simplificado (China),
. chinês tradicional (Taiwan),
. japonês,
. coreano,
. russo,
. francês,
. polonês.

A ótima tradução PT-BR foi produzida e publicada
no Brasil pela Editora Novatec em 2015, sob licença da O'Reilly.

Entre 2020 e 2022, atualizei e expandi bastante o livro para a segunda edição.
Sou muito grato à liderança da
https://www.thoughtworks.com/pt-br[Thoughtworks Brasil]
por todo o apoio que têm me dado nesse projeto.
Quando entreguei o manuscrito para a O'Reilly,
negociei um adendo contratual para liberar a tradução da
segunda edição em PT-BR com uma licença livre,
como uma contribuição para comunidade Python lusófona.

A O'Reilly autorizou que essa tradução fosse publicada sob a licença CC BY-NC-ND:
https://creativecommons.org/licenses/by-nc-nd/4.0/deed.pt_BR[Creative Commons — Atribuição-NãoComercial-SemDerivações 4.0 Internacional].
Com essa mudança contratual,
a Editora Novatec não teve interesse em traduzir e publicar a segunda edição.

Felizmente encontrei meu querido amigo Paulo Candido de Oliveira Filho (PC).
Fomos colegas do ensino fundamental ao médio,
e depois trabalhamos juntos como programadores em diferentes momentos e empresas.
Hoje ele presta serviços editoriais,
inclusive faz traduções com a excelente qualidade desta aqui.

Contratei PC para traduzir. Estou fazendo a revisão técnica,
gerando os arquivos HTML com https://asciidoctor.org/[Asciidoctor]
e publicando em https://PythonFluente.com.
Estamos trabalhando diretamente a partir do _Fluent Python, Second Edition_
da O'Reilly, sem aproveitar a tradução da primeira edição, cujo copyright
pertence à Novatec.

O copyright desta tradução pertence a mim.

_Luciano Ramalho, São Paulo, 13 de março de 2023_


[[data_structures_part]]
= Parte I: Estruturas de dados

include::capitulos/cap01.adoc[]

include::capitulos/cap02.adoc[]

include::capitulos/cap03.adoc[]

include::capitulos/cap04.adoc[]

include::capitulos/cap05.adoc[]

include::capitulos/cap06.adoc[]

= Parte II: Funções como objetos

include::capitulos/cap07.adoc[]

include::capitulos/cap08.adoc[]

include::capitulos/cap09.adoc[]

== 🚧 Padrões de projeto com funções de primeira classe

= Parte III: Classes e protocolos

== 🚧 Um objeto pythônico

== 🚧 Métodos especiais para sequências

include::capitulos/cap13.adoc[]

== 🚧 Herança: para o bem ou para o mal

== 🚧 Mais sobre dicas de tipo

== 🚧 Sobrecarga de operadores

= Parte IV: Controle de fluxo

== 🚧 Iteradores, geradores e corrotinas clássicas

include::capitulos/cap18.adoc[]

include::capitulos/cap19.adoc[]

include::capitulos/cap20.adoc[]

include::capitulos/cap21.adoc[]

= Parte V: Metaprogramação

== 🚧 Atributos dinâmicos e propriedades

== 🚧 Descritores de atributos

== 🚧 Metaprogramação com classes