= Python Fluente, Segunda Edição (2023)
:doctype: book
:author: Luciano Ramalho
:lang: pt_BR
:language: asciidoctor
include::atributos-pt_BR.adoc[]
:xrefstyle: short
:sectnums:
:sectlinks:
:data-uri:
:toc: left
:toclevels: 2
:!chapter-signifier:

[preface]
== Sobre esta tradução

_Python Fluente, Segunda Edição_
é uma tradução direta de _Fluent Python, Second Edition_ (O'Reilly, 2022).
Não é uma obra derivada de _Python Fluente_ (Novatec, 2015).

A presente tradução foi autorizada pela O'Reilly Media para distribuição nos termos da licença
https://creativecommons.org/licenses/by-nc-nd/4.0/deed.pt_BR[CC BY-NC-ND].
Os arquivos-fonte em formato _Asciidoc_ estão no repositório público
https://github.com/pythonfluente/pythonfluente2e.


[NOTE]
====
Esta tradução está em construção, mas todos os capítulos já estão no ar.

Se um link aparece entre colchetes <<assim>>, ele não funciona porque é
uma referência cruzada para alguma parte ainda não traduzida (como o prefácio),
ou pode ser um erro que precisa ser reportado. Contamos com sua colaboração!

Correções e sugestões de melhorias são muito bem vindas!
Para contribuir, veja os
https://github.com/pythonfluente/pythonfluente2e/issues[__issues__]
no repositório https://github.com/pythonfluente/pythonfluente2e.
====

=== Histórico das traduções

Escrevi a primeira e a segunda edições deste livro originalmente em inglês,
para serem mais facilmente distribuídas no mercado internacional.

Cedi os direitos exclusivos para a O'Reilly Media,
nos termos usuais de contratos com editoras famosas:
elas ficam com a maior parte do lucro, o direito de publicar, e
o direito de vender licenças para tradução em outros idiomas.

Até 2022, a primeira edição foi publicada nesses idiomas:

. inglês,
. português brasileiro,
. chinês simplificado (China),
. chinês tradicional (Taiwan),
. japonês,
. coreano,
. russo,
. francês,
. polonês.

A ótima tradução PT-BR foi produzida e publicada
no Brasil pela Editora Novatec em 2015, sob licença da O'Reilly.

Entre 2020 e 2022, atualizei e expandi bastante o livro para a segunda edição.
Sou muito grato à liderança da
https://www.thoughtworks.com/pt-br[Thoughtworks Brasil]
por terem me apoiado enquanto passei a maior parte de 2020 e 2021
pesquisando, escrevendo, e revisando esta edição.

Quando entreguei o manuscrito para a O'Reilly,
negociei um adendo contratual para liberar a tradução da
segunda edição em PT-BR com uma licença livre,
como uma contribuição para comunidade Python lusófona.

A O'Reilly autorizou que essa tradução fosse publicada sob a licença CC BY-NC-ND:
https://creativecommons.org/licenses/by-nc-nd/4.0/deed.pt_BR[Creative Commons — Atribuição-NãoComercial-SemDerivações 4.0 Internacional].
Com essa mudança contratual,
a Editora Novatec não teve interesse em traduzir e publicar a segunda edição.

Felizmente encontrei meu querido amigo Paulo Candido de Oliveira Filho (PC).
Fomos colegas do ensino fundamental ao médio,
e depois trabalhamos juntos como programadores em diferentes momentos e empresas.
Hoje ele presta serviços editoriais,
inclusive faz traduções com a excelente qualidade desta aqui.

Contratei PC para traduzir. Estou fazendo a revisão técnica,
gerando os arquivos HTML com https://asciidoctor.org/[Asciidoctor]
e publicando em https://PythonFluente.com.
Estamos trabalhando diretamente a partir do _Fluent Python, Second Edition_
da O'Reilly, sem aproveitar a tradução da primeira edição, cujo copyright
pertence à Novatec.

O copyright desta tradução pertence a mim.

_Luciano Ramalho, São Paulo, 13 de março de 2023_


[[data_structures_part]]
= Parte I: Estruturas de dados

include::capitulos/cap01.adoc[]

include::capitulos/cap02.adoc[]

include::capitulos/cap03.adoc[]

include::capitulos/cap04.adoc[]

include::capitulos/cap05.adoc[]

include::capitulos/cap06.adoc[]

= Parte II: Funções como objetos

include::capitulos/cap07.adoc[]

include::capitulos/cap08.adoc[]

include::capitulos/cap09.adoc[]

include::capitulos/cap10.adoc[]

= Parte III: Classes e protocolos

include::capitulos/cap11.adoc[]

include::capitulos/cap12.adoc[]

include::capitulos/cap13.adoc[]

include::capitulos/cap14.adoc[]

include::capitulos/cap15.adoc[]

include::capitulos/cap16.adoc[]

= Parte IV: Controle de fluxo

include::capitulos/cap17.adoc[]

include::capitulos/cap18.adoc[]

include::capitulos/cap19.adoc[]

include::capitulos/cap20.adoc[]

include::capitulos/cap21.adoc[]

= Parte V: Metaprogramação

include::capitulos/cap22.adoc[]

include::capitulos/cap23.adoc[]

include::capitulos/cap24.adoc[]