= Python Fluente, Segunda Edição (2023)
:doctype: book
:author: Luciano Ramalho
:lang: pt_BR
:language: asciidoctor
include::atributos-pt_BR.adoc[]
:xrefstyle: short
:sectnums:
:sectlinks:
:data-uri:
:toc:
:toclevels: 2
:!chapter-signifier:

[preface]
== Sobre esta tradução

_Python Fluente, Segunda Edição_
é uma tradução direta de _Fluent Python, Second Edition_ (O'Reilly, 2022).
Não é uma obra derivada de _Python Fluente_ (Novatec, 2015).

Esta tradução está sendo produzida sob autorização da O'Reilly, nos termos da licença 
https://creativecommons.org/licenses/by-nc-nd/4.0/deed.pt_BR[CC BY-NC-ND].
Os arquivos-fonte em formato _Asciidoc_ estão no repositório público 
https://github.com/pythonfluente/pythonfluente2e.

=== Histórico

Escrevi a primeira e a segunda edições deste livro originalmente em inglês,
para que o livro fosse mais facilmente distribuído no mercado internacional.

Cedi os direitos exclusivos para a O'Reilly Media,
nos termos usuais de contrato com editoras famosas:
elas ficam com a maior parte do lucro, o direito de publicar, e
o direito de vender licenças para tradução em outros idiomas.

A primeira edição foi publicada em nove idiomas até 2022:
inglês, português brasileiro, japonês, coreano, russo, francês, polonês,
chinês simplificado, e chinês tradicional (Taiwan).
A tradução em português foi produzida e publicada pela Editora Novatec
em 2015, sob licença da O'Reilly.

Em 2022, entreguei o manuscrito da segunda edição para a O'Reilly,
e negociei um adendo contratual para liberar a 
tradução da segunda edição em PT-BR com uma licença livre, como
uma contribuição para comunidade Python lusófona.
A O'Reilly autorizou esta tradução sob a licença CC BY-NC-ND:
https://creativecommons.org/licenses/by-nc-nd/4.0/deed.pt_BR[Creative Commons — Atribuição-NãoComercial-SemDerivações 4.0 Internacional].
Com essa mudança contratual, a Editora Novatec não teve interesse de traduzir
e publicar a segunda edição.

Felizmente encontrei meu amigo Paulo Candido de Oliveira Filho (PC),
com quem trabalhei vários anos programando.
Hoje ele presta serviços editoriais,
inclusive traduções com a excelente qualidade desta aqui.

Contratei PC para fazer a tradução, e estou fazendo a revisão técnica,
gerando os arquivos HTML e publicando em http://PythonFluente.com.
Estamos trabalhando diretamente a partir do _Fluent Python, Second Edition_
da O'Reilly, sem aproveitar a tradução da primeira edição cujo copyright
pertence à Novatec.

O copyright desta tradução pertence a mim.

_Luciano Ramalho, São Paulo, 13 de março de 2023_



[NOTE]
====
Esta é uma tradução em construção do livro _Fluent Python, Second Edition_.
No sumário, capítulos ainda não traduzidos estão marcados com o símbolo 🚧 (em obras).

Priorizamos os capítulos 6, 8, 13, 19, 20, e 21. para apoiar o curso _Python Engineer_
a ser lançado pela https://www.linuxtips.io/[LINUXtips] em 2023.
Depois do capítulo 21, os capítulos restantes serão traduzidos em ordem do 1 ao 24.

No momento não precisamos de ajuda para traduzir, mas correções ou
sugestões de melhorias são muito bem vindas!
Para contribuir, veja os 
https://github.com/pythonfluente/pythonfluente2e/issues[__issues__]
no repositório https://github.com/pythonfluente/pythonfluente2e. 
====

[[data_structures_part]]
= Parte I: Estruturas de dados

== 🚧 Modelo de dados de Python

== 🚧 Uma coleção de sequências

== 🚧 Dicionários e conjuntos

== 🚧 Texto versus bytes

== 🚧 Fábricas de classes de dados

include::capitulos/cap06.adoc[]

= Parte II: Funções como objetos

== 🚧 Funções como objetos de primeira classe

include::capitulos/cap08.adoc[]

== 🚧 Decoradores e closures

== 🚧 Padrões de projeto com funções de primeira classe

== 🚧 Um objeto pythônico

== 🚧 Métodos especiais para sequências

include::capitulos/cap13.adoc[]
