[colophon%discrete%notitle%nonfacing,toclevels=0]
= Copyright
:isbn-pb: 978-65-989778-3-2
:isbn-cor: 978-65-989778-2-5

Tradução autorizada em português de
_Fluent Python, 2nd Edition_ + 
ISBN 978-1-492-05635-5
© 2022 Luciano Ramalho. +
Esta tradução é publicada e vendida com a permissão da O'Reilly Media, Inc.,
detentora dos direitos para publicação e venda desta obra.

© 2025 Luciano Ramalho. +
_Python Fluente, 2ª edição_ está publicado sob a licença
CC BY-NC-ND 4.0 +
_Atribuição-NãoComercial-SemDerivações 4.0 Internacional_ [.small]#&#91;fpy.li/ccby&#93;#. +
O autor mantém uma versão online em https://PythonFluente.com.

Autor: Luciano Ramalho +
Título: Python Fluente, 2ª edição, volume 2: classes e protocolos +
Primeira edição: 2015 +
Edição atual: janeiro/2026 +
Revisão: `pyfl2-vol2-pb-2026-01-15.pdf`

Tradução da 2ª edição: Paulo Candido de Oliveira Filho +
Ilustração de capa: Thiago Castor (xilogravura "Calango") +
Design da capa: Luciano Ramalho, Zander Catta Preta @ Z•Edições +
Design do miolo: Luciano Ramalho, com Asciidoctor +
Ficha catalográfica: Edison Luís dos Santos

Publisher: Heinar Maracy @ Z•Edições

----
R135p   Ramalho, Luciano.

        Python Fluente, 2a edição, volume 2: classes e protocolos /
        Luciano Ramalho - São Paulo, SP - Z.Edições, 2025.
        364 p.; il.; 17 cm × 24 cm

        ISBN: 978-65-989778-3-2
        1.Informática. 2.Linguagem de Programação. 3.Python.
        4.Metaprogramação.

        I.Título II.Dados e funções III.RAMALHO, Luciano.

                                                            CDU: 004.438
                                                            CDD: 005.133
----
