[colophon%discrete%notitle%nonfacing,toclevels=0]
= Copyright
:volume: 3-pb
:isbn-pb: 978-65-989778-1-8
:isbn-cor: 978-65-989778-6-3 

Tradução autorizada em português de
_Fluent Python, 2nd Edition_ + 
ISBN 978-1-492-05635-5
© 2022 Luciano Ramalho. +
Esta tradução é publicada e vendida com a permissão da O'Reilly Media, Inc.,
detentora dos direitos para publicação e venda desta obra.

© 2025 Luciano Ramalho. +
_Python Fluente, 2ª edição_ está publicado sob a licença
CC BY-NC-ND 4.0 +
https://fpy.li/ccby[_Atribuição-NãoComercial-SemDerivações 4.0 Internacional_] +
O autor mantém uma versão online em https://PythonFluente.com.

Autor: Luciano Ramalho +
Título: Python Fluente, 2ª edição, volume 3: Fluxo e Metaprogramação +
1ª edição: 2015 +
2ª edição: 2022 +
Revisão: `pyfl2-vol3-pb-2026-03-03.pdf`

Tradução da 2ª edição: Paulo Candido de Oliveira Filho +
Ilustração de capa: Thiago Castor (xilogravura "Calango") +
Design da capa: Luciano Ramalho, Zander Catta Preta @ Z•Edições +
Design do miolo: Luciano Ramalho, com Asciidoctor +
Ficha catalográfica: Edison Luís dos Santos

Publisher: Heinar Maracy @ Z•Edições

----
R135p   Ramalho, Luciano.

        Python Fluente, 2ª edição, volume 3: Fluxo e Metaprogramação /
        Luciano Ramalho - São Paulo, SP - Z.Edições, 2025.
        459 p.; il.; 17 cm × 24 cm

        ISBN: 978-65-989778-1-8
        1.Informática. 2.Linguagem de Programação. 3.Python.
        4.Metaprogramação.

        I.Título II.Fluxo e Metaprogramação III.RAMALHO, Luciano.

                                                            CDU: 004.438
                                                            CDD: 005.133
----
