# This Action uses minimal steps to run in ~5 seconds to rapidly:
# lint Python code using ruff which provides intuitive GitHub Annotations to contributors.
# https://docs.astral.sh/ruff/

name: ci
on:
  push:
    # branches: [main]
  pull_request:
    # branches: [main]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
      with:
        args: check --ignore=ALL  # Turn off 800+ lint rules to only look for Python SyntaxErrors.
